FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY collab-server ./collab-server
COPY lib ./lib
RUN mkdir -p /app/data

ENV COLLAB_PORT 1234
EXPOSE 1234

CMD ["node", "collab-server/server.js"]
